language: go
go: 
  - 1.11.x

env:
  - GO111MODULE=on


go_import_path: github.com/yandex/pandora

before_install:
  - mkdir $HOME/tools
  - GOPATH=$HOME/tools make tools
  - export PATH=$HOME/tools/bin:$PATH
  - make deps

script: make travis
